### ISSUE TITLE
Only the broadcaster should be shown?

### ISSUE THREAD

**Issue by nickburrett** [AgoraIO/Agora-WordPress#103] opened 2021-03-29 13:51 UTC
I am using the shortcode:
[agora-broadcast channel_id="11"  videoProfile="720p_3"]

I am the only person broadcasting, the viewer clicks "Watch the live screen".
The number top left changes from 1 to 2.
The page now shows my broadcast plus an extra space?

As the only broadcaster, the only thing that should be shown in my broadcast?

![Screenshot 2021-03-29 at 14 36 37](https://user-images.githubusercontent.com/9543168/112846237-bcfe9c00-909d-11eb-8c74-13f949f81420.png)

**Comment by digitallysavvy** [comment] 2021-04-08 18:54
@nickburrett thank you for the interest in the Agora Video for WordPress plugin. The counter you are referencing is meant to show the number of people in the channel, so by design in Broadcast mode it shows you the total count of hosts and audience members. 

You can modify the plugin to only count the host.

**Comment by digitallysavvy** [comment] 2021-04-08 18:55
> The page now shows my broadcast plus an extra space?
This sounds like a bug. are you able to share more details about the WP installation, what theme are you using, any plugins?

**Comment by nickburrett** [comment] 2021-04-09 10:55
I am using Wordpress 5.7
I am using the theme "Hello Elementor"
I am using the plugin "Elementor"

Here is a video of what happens:
[https://www.dropbox.com/s/ca6ohxhouv7oy75/WEBRTC.mp4?dl=0](https://www.dropbox.com/s/ca6ohxhouv7oy75/WEBRTC.mp4?dl=0)

**Comment by nickburrett** [comment] 2021-06-09 06:48
@digitallysavvy any update on this please?

**Comment by digitallysavvy** [comment] 2021-06-10 03:24
@nickburrett Originally I was waiting till v3 to do a release, but I've got a patch release  I'm working on next week, so  I'll work on a fix for this issue as well.

**Comment by nickburrett** [comment] 2021-08-10 08:17
Did this get fixed?

**Comment by digitallysavvy** [comment] 2021-08-13 03:12
@nickburrett this issue has been resolved as part of the v3 update. V3 is currently available for download as part of the public v3 beta (https://bit.ly/37p4aKT)

**Closed** 2021-08-13 03:15 UTC
Labels: bug
