### ISSUE TITLE
[BUG] Screen Share fails on Safari 13.1.1 on branch 3.0.0.beta

### ISSUE THREAD

**Issue by umeshpatwari** [AgoraIO/Agora-WordPress#111] opened 2021-09-08 07:10 UTC
I am using Agora 3.0.0.beta3 plugin when i share my screen on safari i got error nothing to share but in chrome is working fine.

**Comment by digitallysavvy** [comment] 2021-09-08 16:22
@umeshpatwari please file this issue using the "Bug" template and provide the required information.

**Comment by digitallysavvy** [comment] 2021-09-08 16:23
the requirements in the Bug Report template are important for our team to get the issue resolved in a timely manner.

**Closed by digitallysavvy** 2021-09-08 16:22 UTC
Labels: bug

**Comment by digitallysavvy** [comment] 2021-09-08 16:48
@umeshpatwari to provide some context as to why I closed the issue is because I tested using Safari and Chrome and for both screen sharing works. This image below shows ScreenSharing from Safari using v3.0.0.beta3

<img width="1680" alt="Screen Shot 2021-09-08 at 12 35 06 PM" src="https://user-images.githubusercontent.com/6816583/132549395-05d1d900-7596-4760-9afb-002a389a831a.png">

Two things should be noted:

1. When screen sharing, by design the plugin does not play the ScreenShare stream for the user that is sharing their screen to avoid the "vortex" effect. 

2. When screen sharing on Safari it does not give the same controls to the end user as Chrome. For example in Chrome when initializing the screen sharing it allows the user to select between full screen, app window, or chrome tab. Conversely Apple requires the developer to make this decision within the code, so by design the plugin automatically chooses to share the entire screen. 

If you are still having issues with screen share on Safari it's important for you to file a [bug report](https://github.com/AgoraIO/Agora-WordPress/issues/new?assignees=digitallysavvy&labels=bug&template=bug_report.md&title=%5BBUG%5D) to capture any additional information that can help the team to identify the issue you are facing. 

If you are experiencing the plugin as it is intended but would like to change the default behavior,  please file a [feature request](https://github.com/AgoraIO/Agora-WordPress/issues/new?assignees=digitallysavvy&labels=enhancement&template=feature_request.md&title=%5BFEATURE%5D) and we can consider how to add this as a setting.
